#!/usr/bin/env bash

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
LEAN_ROOT="$REPO_ROOT/lean"
INVENTORY="$LEAN_ROOT/THEOREM_INVENTORY.md"
tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT

imports="$tmp_dir/imports.txt"
sources="$tmp_dir/sources.txt"
generated="$tmp_dir/THEOREM_INVENTORY.md"

while read -r _ module; do
  module_path="$(printf '%s\n' "$module" | tr '.' '/')"
  path="$LEAN_ROOT/$module_path.lean"
  if [[ ! -f "$path" ]]; then
    echo "FAIL: root module imports missing source: $module" >&2
    exit 1
  fi
  printf '%s\n' "$path"
done < <(grep -E '^import Mossaic\.' "$LEAN_ROOT/Mossaic.lean") | sort > "$imports"

find "$LEAN_ROOT/Mossaic" -type f -name '*.lean' | sort > "$sources"
if ! cmp -s "$imports" "$sources"; then
  echo "FAIL: lean/Mossaic.lean must import every proof module exactly once." >&2
  diff -u "$imports" "$sources" || true
  exit 1
fi

total=0
{
  echo "# Mossaic Theorem Inventory"
  echo
  echo "Generated by \`lean/scripts/theorem-inventory.sh --write\`."
  echo "The check derives the corpus from \`lean/Mossaic.lean\` and fails if a proof module is omitted."
  echo "Counts include public top-level \`theorem\` declarations and exclude \`private theorem\` helpers."
  echo
  echo "| Imported module | Public theorems |"
  echo "|---|---:|"
  while IFS= read -r file; do
    module="${file#"$LEAN_ROOT/"}"
    count="$(grep -Ec '^theorem[[:space:]]+' "$file" || true)"
    total=$((total + count))
    printf '| `%s` | %d |\n' "$module" "$count"
  done < "$imports"
  printf '| **Total** | **%d** |\n' "$total"
  echo
  echo "## Declarations"
  while IFS= read -r file; do
    module="${file#"$LEAN_ROOT/"}"
    declarations="$(grep -E '^theorem[[:space:]]+' "$file" || true)"
    if [[ -z "$declarations" ]]; then
      continue
    fi
    printf '\n### `%s`\n\n' "$module"
    while IFS= read -r declaration; do
      name="$(printf '%s\n' "$declaration" | sed -E 's/^theorem[[:space:]]+([^[:space:]:({]+).*/\1/')"
      printf -- '- `%s`\n' "$name"
    done <<< "$declarations"
  done < "$imports"
} > "$generated"

case "${1:-}" in
  --write)
    mv "$generated" "$INVENTORY"
    echo "Wrote theorem inventory: $total public declarations."
    ;;
  --check)
    if [[ ! -f "$INVENTORY" ]] || ! cmp -s "$generated" "$INVENTORY"; then
      echo "FAIL: theorem inventory is stale; run: bash lean/scripts/theorem-inventory.sh --write" >&2
      if [[ -f "$INVENTORY" ]]; then
        diff -u "$INVENTORY" "$generated" || true
      fi
      exit 1
    fi
    echo "OK: theorem inventory matches $total public declarations across the imported corpus."
    ;;
  "")
    cat "$generated"
    ;;
  *)
    echo "Usage: $0 [--check|--write]" >&2
    exit 2
    ;;
esac
